"""
Database models for the core app
"""
from django.conf import settings
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)

import uuid
import os


def recipe_image_file_path(instance, filename):
    """Generate file path for new recipe image"""
    ext = os.path.splitext(filename)[1]  # Get the file extension from the filename # noqa
    filename = f"{uuid.uuid4()}{ext}"  # Generate a new filename with a random UUID # noqa

    # os.path.join is platform independent. It joins the path components into a single path # noqa
    return os.path.join("uploads", "recipe", filename)


class UserManager(BaseUserManager):
    """This is a custom user manager class
    which is created by extending the BaseUserManager"""

    def create_user(self, email, password=None, **extra_fields):
        """Create, save and return a new user"""
        if not email:
            raise ValueError("Users must have an email address")

        # self.model is a reference to the model that the manager is for.
        user = self.model(email=self.normalize_email(email), **extra_fields)

        # set_password is a built-in function of the AbstractBaseUser class which hashes the password # noqa
        user.set_password(password)

        # save(using=self._db) is used to save the user to the User table in the database # noqa
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """Create and return a super user"""

        if not email:
            raise ValueError("Super user must have an email address")

        user = self.create_user(email, password)

        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        # return the usr instance, not class
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """This is a custom user model which is created by extending the AbstractBaseUser and PermissionsMixin # noqa
    AbstractBaseUser contains the functionality for the Authentication system # noqa
    PermissionsMixin contains the functionality for the Permissions system # noqa"""

    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = (
        UserManager()
    )  # This is used to tell Django that UserManager is the manager for the User model # noqa

    USERNAME_FIELD = "email"


class UserDetails(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # One-to-one relationship with the User model # noqa
    age = models.IntegerField()
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    favorite_food = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.user.email} - Details'


class Recipe(models.Model):
    """Recipe model based on Django's basic built-in models.Model class"""

    # ForeignKey is used to create a many-to-one relationship between the Recipe model and the User model # noqa
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,  # If the user is deleted, delete the recipe as well # noqa
    )

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    time_minutes = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    link = models.CharField(max_length=255, blank=True)

    tags = models.ManyToManyField("Tag")  # Many-to-many relationship with the Tag model. Many recipes can have many tags # noqa
    ingredients = models.ManyToManyField("Ingredient")  # Many-to-many relationship with the Ingredient model. Many recipes can have many ingredients # noqa

    image = models.ImageField(null=True, upload_to=recipe_image_file_path) # Image name is generated by recipe_image_file_path function # noqa

    def __str__(self):
        return self.title


class Tag(models.Model):
    """Tag model for filtering, based on Django's basic built-in models.Model class""" # noqa

    name = models.CharField(max_length=255)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,  # If the user is deleted, delete the tag as well # noqa
    )

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    """Ingredient model for recipe, based on Django's basic built-in models.Model class""" # noqa

    name = models.CharField(max_length=255)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,  # If the user is deleted, delete the ingredient as well # noqa
    )

    def __str__(self):
        return self.name
